###################################################################
# flag
###################################################################

MOD_SRC  = 
MOD_OBJ  = $(D_ROOT)/out

###################################################################
# source files
# - add your file here !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
###################################################################

MOD_SRC  := \
	bmt.c \
	circbuf.c \
	dramc_dqs_gw.c  \
	dramc_calib.c \
	mmc_common_inter.c \
	mmc_core.c \
	mmc_test.c \
	msdc.c \
	msdc_utils.c \
	addr_trans.c \
	mt_i2c.c \
	mtk_key.c \
	mt_pmic6329.c \
	mt_rtc.c \
	mt_usbd.c \
	mt_usbphy.c \
	mt_usbtty.c \
	mt_emi.c \
	mt_cpu_power.c \
	mtk_timer.c \
	mtk_wdt.c \
	nand.c \
	nand_common_inter.c \
	partition_mt.c \
	platform.c \
	pll.c \
	device_apc.c \
	gpio.c \
	uart.c

###################################################################
# target
###################################################################

include $(COMMON_FILE_MK)
