###################################################################
# flag
###################################################################

MOD_SRC  = 
MOD_OBJ  = $(D_ROOT)/out

###################################################################
# source files
# - add your file here !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
###################################################################

MOD_SRC  := \
	blkdev.c \
	div0.c \
	download.c \
	download_legacy.c \
	download_legacy_utils.c \
	eabi_uldivmod.s \
	eabi_idiv.s \
	eabi.s \
	handshake_uart.c \
	handshake_usb.c \
	main.c \
	part.c \
	print.c \
	stdlib.c \
	string.c

###################################################################
# target
###################################################################

include $(COMMON_FILE_MK)
