/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2008
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*****************************************************************************
 *
 * Filename:
 * ---------
 *   ccci_ch.h
 *
 * Project:
 * --------
 *   YuSu
 *
 * Description:
 * ------------
 *   MT6516 CCCI channel definitions
 *
 * Author:
 * -------
 *   CC Hwang (mtk00702)
 *
 ****************************************************************************/

#if defined(X_DEF_CH)
#define CCCI_CH_X(a, b) a = b,
#endif  /* X_DEF_CH */

#if defined(X_DEF_CTRL)
#define CCCI_CH_X(a, b) __ATTR(a, 0644, NULL, NULL),
#endif  /* X_DEF_CTRL */

#if defined(X_DEF_ATTR)
#define CCCI_CH_X(a, b) &(ccci_ctrl[a].attr),
#endif  /* X_DEF_ATTR */

CCCI_CH_X(CCCI_CONTROL_RX, 0)
CCCI_CH_X(CCCI_CONTROL_TX, 1)
CCCI_CH_X(CCCI_SYSTEM_RX, 2)
CCCI_CH_X(CCCI_SYSTEM_TX, 3)
CCCI_CH_X(CCCI_PCM_RX, 4)
CCCI_CH_X(CCCI_PCM_TX, 5)
CCCI_CH_X(CCCI_UART1_RX, 6)
CCCI_CH_X(CCCI_UART1_RX_ACK, 7)
CCCI_CH_X(CCCI_UART1_TX, 8)
CCCI_CH_X(CCCI_UART1_TX_ACK, 9)
CCCI_CH_X(CCCI_UART2_RX, 10)
CCCI_CH_X(CCCI_UART2_RX_ACK, 11)
CCCI_CH_X(CCCI_UART2_TX, 12)
CCCI_CH_X(CCCI_UART2_TX_ACK, 13)
CCCI_CH_X(CCCI_FS_RX, 14)
CCCI_CH_X(CCCI_FS_TX, 15)
CCCI_CH_X(CCCI_PMIC_RX, 16)
CCCI_CH_X(CCCI_PMIC_TX, 17)
CCCI_CH_X(CCCI_UEM_RX, 18)
CCCI_CH_X(CCCI_UEM_TX, 19)

#undef CCCI_CH_X
